services:
  nifi-registry:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  conf-vol:
    name: ${CONF_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  database-vol:
    name: ${DATABASE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  flow-storage-vol:
    name: ${FLOW_STORAGE_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  security-vol:
    name: ${SECURITY_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
